name: Pulumi
on:
  pull_request:
    branches:
      - main

jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./python
    steps:
      - uses: actions/checkout@v3
    #   - name: Login
    #     uses: docker://pulumi/actions:v1.0.0
    #     with:
    #         args: login gs://xxx
    #     env:
    #         PULUMI_CREDENTIALS_PATH: /github/home/.pulumi
      - uses: actions/setup-node@v3.5.0
        with:
            # node-version-file: package-lock.json
            cache-dependency-path: '**/python/package-lock.json'
      - run: npm install
        working-directory: ./python
      - name: install digital ocean 
        id: install_do
        run: pip3 install pulumi pulumi_digitalocean
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: kicka5h/sprinkle-pages/lab
          work-dir: 'python'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_PAT }}