name: Pulumi
on:
  pull_request:
    branches:
      - main
jobs:
  up:
    name: Preview
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: kicka5h/sprinkle-pages
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_PAT }}