name: Pulumi
on:
  workflow_dispatch:

jobs:
  up:
    name: Update
    runs-on: ubuntu-latest
    environment: 
        name: deployment-approvers
    defaults:
        run:
            working-directory: ./python
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.5.0
        with:
            # node-version-file: package-lock.json
            cache-dependency-path: '**/python/package-lock.json'
      - run: npm install
        working-directory: ./python
      - run: export DIGITALOCEAN_TOKEN=${{ secrets.do_token }}
      - uses: pulumi/actions@v4
        with:
          command: update
          stack-name: kicka5h/sprinkle-pages/lab
          work-dir: 'python'
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_PAT }}